/*
 * JS for Give_Answer generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function Give_Answer_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblSelectQuestion': 'Give_Answer_lblSelectQuestion',
        'sltQuestions': 'Give_Answer_sltQuestions',
        'sltQuestions-0': 'Give_Answer_sltQuestions-0',
        'txtViewQuestion': 'Give_Answer_txtViewQuestion',
        'txtAnswer': 'Give_Answer_txtAnswer',
        'btnSubmitAnswer': 'Give_Answer_btnSubmitAnswer'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_0"] = {
        "homeScreen": "Give_Answer",
        "directions": []
    };
    Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_1"] = {
        "homeScreen": "Give_Answer",
        "directions": [
            {
                "from_name": "Give_Answer",
                "from_type": "UI",
                "to_name": "QuestionStore1",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['sltQuestions:selectedMenuItem']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_2"] = {
        "homeScreen": "Give_Answer",
        "directions": [
            {
                "from_name": "QuestionStore1",
                "from_type": "LOCAL_STORAGE",
                "to_name": "Give_Answer",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['txtViewQuestion:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Give_Answer_listQuestionload_onsuccess_mapping_0"] = {
        "homeScreen": "Give_Answer",
        "directions": [
            {
                "from_name": "listQuestionload",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "Give_Answer",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]['Question']",
                        "target": "$['sltQuestions-0:value']"
                    },
                    {
                        "source": "$['body'][i]['Question']",
                        "target": "$['sltQuestions-0:label']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target": "$['sltQuestions-0']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["Give_Answer_listQuestionload_onbeforesend_mapping_0"] = {
        "homeScreen": "Give_Answer",
        "directions": [
            {
                "to_name": "listQuestionload",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["Give_Answer_createAnswer_onsuccess_mapping_0"] = {
        "homeScreen": "Give_Answer",
        "directions": []
    };
    Apperyio.mappings["Give_Answer_createAnswer_onbeforesend_mapping_0"] = {
        "homeScreen": "Give_Answer",
        "directions": [
            {
                "from_name": "Give_Answer",
                "from_type": "UI",
                "to_name": "createAnswer",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['sltQuestions:selectedMenuItem']",
                        "target": "$['body']['Question']"
                    },
                    {
                        "source": "$['txtAnswer:text']",
                        "target": "$['body']['Answer']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.listQuestionload = Apperyio.datasources.listQuestionload = new Apperyio.DataSource(Question_and_Answer_Question_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_listQuestionload_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_listQuestionload_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createAnswer = Apperyio.datasources.createAnswer = new Apperyio.DataSource(Question_and_Answer_Question_and_Answer_Collection_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_createAnswer_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_createAnswer_onsuccess_mapping_0"]);
            alert("Answer uploaded successfully");
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'Give_Answer';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Give_Answer_onLoad = function() {
        Give_Answer_elementsExtraJS();
        try {
            listQuestionload.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        Give_Answer_deviceEvents();
        Give_Answer_windowEvents();
        Give_Answer_elementsEvents();
    };
    // screen window events
    function Give_Answer_windowEvents() {
        $('#Give_Answer').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Give_Answer_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Give_Answer_elementsExtraJS() {
        // screen (Give_Answer) extra code
        /* sltQuestions */
        $("#Give_Answer_sltQuestions").parent().find("a.ui-btn").attr("tabindex", "1");
    };
    // screen elements handler
    function Give_Answer_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("change", '#Give_Answer_mobilecontainer [name="sltQuestions"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_0"]);
                Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_1"]);
                Apperyio.processMappingAction(Apperyio.mappings["Give_Answer_sltQuestions_onchange_mapping_2"]);
            },
        }, '#Give_Answer_mobilecontainer [name="sltQuestions"]');
        $(document).off("click", '#Give_Answer_mobilecontainer [name="btnSubmitAnswer"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        createAnswer.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        $a.c15r("txtAnswer", "set", "text", ' ')
                    } catch (e) {
                        console.error(e)
                    };
                }
            },
        }, '#Give_Answer_mobilecontainer [name="btnSubmitAnswer"]');
    };
    $(document).off("pagebeforeshow", "#Give_Answer").on("pagebeforeshow", "#Give_Answer", function(event, ui) {
        Apperyio.CurrentScreen = "Give_Answer";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Give_Answer_onLoad();
};
$(document).off("pagecreate", "#Give_Answer").on("pagecreate", "#Give_Answer", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Give_Answer_js();
});