/*
 * JS for Login generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function Login_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblUserName': 'Login_lblUserName',
        'lblPassword': 'Login_lblPassword',
        'btnlogin': 'Login_btnlogin',
        'spacer_6': 'Login_spacer_6',
        'btnSignUp': 'Login_btnSignUp'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Login_loginService_onsuccess_mapping_0"] = {
        "homeScreen": "Login",
        "directions": []
    };
    Apperyio.mappings["Login_loginService_onbeforesend_mapping_0"] = {
        "homeScreen": "Login",
        "directions": [
            {
                "from_name": "Login",
                "from_type": "UI",
                "to_name": "loginService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['lblUserName:text']",
                        "target": "$['body']['username']"
                    },
                    {
                        "source": "$['lblPassword:text']",
                        "target": "$['body']['password']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.loginService = Apperyio.datasources.loginService = new Apperyio.DataSource(Log_InandSign_Up_database_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Login_loginService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Login_loginService_onsuccess_mapping_0"]);
            alert("Successfully logged in");
            Apperyio.navigateTo('Choose', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("Wrong Username or Password");
        }
    });
    Apperyio.CurrentScreen = 'Login';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Login_onLoad = function() {
        Login_elementsExtraJS();
        Login_deviceEvents();
        Login_windowEvents();
        Login_elementsEvents();
    };
    // screen window events
    function Login_windowEvents() {
        $('#Login').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Login_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Login_elementsExtraJS() {
        // screen (Login) extra code
    };
    // screen elements handler
    function Login_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Login_mobilecontainer [name="btnlogin"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        loginService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#Login_mobilecontainer [name="btnlogin"]');
        $(document).off("click", '#Login_mobilecontainer [name="btnSignUp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Signup', {
                        reverse: false
                    });
                }
            },
        }, '#Login_mobilecontainer [name="btnSignUp"]');
    };
    $(document).off("pagebeforeshow", "#Login").on("pagebeforeshow", "#Login", function(event, ui) {
        Apperyio.CurrentScreen = "Login";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Login_onLoad();
};
$(document).off("pagecreate", "#Login").on("pagecreate", "#Login", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Login_js();
});