/*
 * JS for QuestionandAnswer generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function QuestionandAnswer_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_2': 'QuestionandAnswer_mobilegrid_2',
        'mobilegridcell_3': 'QuestionandAnswer_mobilegridcell_3',
        'btnAskQuestion': 'QuestionandAnswer_btnAskQuestion',
        'mobilegridcell_4': 'QuestionandAnswer_mobilegridcell_4',
        'btnGiveAnswer': 'QuestionandAnswer_btnGiveAnswer',
        'btnViewAnswer': 'QuestionandAnswer_btnViewAnswer'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'QuestionandAnswer';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var QuestionandAnswer_onLoad = function() {
        QuestionandAnswer_elementsExtraJS();
        QuestionandAnswer_deviceEvents();
        QuestionandAnswer_windowEvents();
        QuestionandAnswer_elementsEvents();
    };
    // screen window events
    function QuestionandAnswer_windowEvents() {
        $('#QuestionandAnswer').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function QuestionandAnswer_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function QuestionandAnswer_elementsExtraJS() {
        // screen (QuestionandAnswer) extra code
    };
    // screen elements handler
    function QuestionandAnswer_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#QuestionandAnswer_mobilecontainer [name="btnAskQuestion"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Ask_a_Question', {
                        reverse: false
                    });
                }
            },
        }, '#QuestionandAnswer_mobilecontainer [name="btnAskQuestion"]');
        $(document).off("click", '#QuestionandAnswer_mobilecontainer [name="btnGiveAnswer"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Give_Answer', {
                        reverse: false
                    });
                }
            },
        }, '#QuestionandAnswer_mobilecontainer [name="btnGiveAnswer"]');
        $(document).off("click", '#QuestionandAnswer_mobilecontainer [name="btnViewAnswer"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('View_Answer', {
                        reverse: false
                    });
                }
            },
        }, '#QuestionandAnswer_mobilecontainer [name="btnViewAnswer"]');
    };
    $(document).off("pagebeforeshow", "#QuestionandAnswer").on("pagebeforeshow", "#QuestionandAnswer", function(event, ui) {
        Apperyio.CurrentScreen = "QuestionandAnswer";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    QuestionandAnswer_onLoad();
};
$(document).off("pagecreate", "#QuestionandAnswer").on("pagecreate", "#QuestionandAnswer", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    QuestionandAnswer_js();
});