/*
 * JS for ReportPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function ReportPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblSelectDestination': 'ReportPage_lblSelectDestination',
        'sltSelectPosition': 'ReportPage_sltSelectPosition',
        'sltSelectPosition-0': 'ReportPage_sltSelectPosition-0',
        'spacer_4': 'ReportPage_spacer_4',
        'txtSubject': 'ReportPage_txtSubject',
        'spacer_6': 'ReportPage_spacer_6',
        'txtEnterEmail': 'ReportPage_txtEnterEmail',
        'btnSendEmail': 'ReportPage_btnSendEmail'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["ReportPage_listSelectPosition_onsuccess_mapping_0"] = {
        "homeScreen": "ReportPage",
        "directions": [
            {
                "from_name": "listSelectPosition",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "ReportPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]['Positions']",
                        "target": "$['sltSelectPosition-0:label']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target": "$['sltSelectPosition-0']"
                    },
                    {
                        "source": "$['body'][i]['Email']",
                        "target": "$['sltSelectPosition-0:value']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["ReportPage_listSelectPosition_onbeforesend_mapping_0"] = {
        "homeScreen": "ReportPage",
        "directions": [
            {
                "to_name": "listSelectPosition",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["ReportPage_sendEmailService_onsuccess_mapping_0"] = {
        "homeScreen": "ReportPage",
        "directions": []
    };
    Apperyio.mappings["ReportPage_sendEmailService_onbeforesend_mapping_0"] = {
        "homeScreen": "ReportPage",
        "directions": [
            {
                "from_name": "ReportPage",
                "from_type": "UI",
                "to_name": "sendEmailService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {},
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['sltSelectPosition:selectedMenuItem']",
                        "target": "$['parameters']['to']"
                    },
                    {
                        "source": "$['txtSubject:text']",
                        "target": "$['parameters']['subject']"
                    },
                    {
                        "source": "$['txtEnterEmail:text']",
                        "target": "$['parameters']['text']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.listSelectPosition = Apperyio.datasources.listSelectPosition = new Apperyio.DataSource(StudentGuideDatabase_ReportCollection_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ReportPage_listSelectPosition_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ReportPage_listSelectPosition_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.sendEmailService = Apperyio.datasources.sendEmailService = new Apperyio.DataSource(SendGridEmail_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ReportPage_sendEmailService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ReportPage_sendEmailService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'ReportPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var ReportPage_onLoad = function() {
        ReportPage_elementsExtraJS();
        try {
            listSelectPosition.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        ReportPage_deviceEvents();
        ReportPage_windowEvents();
        ReportPage_elementsEvents();
    };
    // screen window events
    function ReportPage_windowEvents() {
        $('#ReportPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function ReportPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function ReportPage_elementsExtraJS() {
        // screen (ReportPage) extra code
        /* sltSelectPosition */
        $("#ReportPage_sltSelectPosition").parent().find("a.ui-btn").attr("tabindex", "1");
    };
    // screen elements handler
    function ReportPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#ReportPage_mobilecontainer [name="btnSendEmail"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        sendEmailService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        $a.c15r("txtEnterEmail", "set", "text", ' ')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("txtSubject", "set", "text", ' ')
                    } catch (e) {
                        console.error(e)
                    };
                }
            },
        }, '#ReportPage_mobilecontainer [name="btnSendEmail"]');
    };
    $(document).off("pagebeforeshow", "#ReportPage").on("pagebeforeshow", "#ReportPage", function(event, ui) {
        Apperyio.CurrentScreen = "ReportPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    ReportPage_onLoad();
};
$(document).off("pagecreate", "#ReportPage").on("pagecreate", "#ReportPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ReportPage_js();
});