/*
 * JS for Signup generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function Signup_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblUserName': 'Signup_lblUserName',
        'lblPassword': 'Signup_lblPassword',
        'btnSignUp': 'Signup_btnSignUp'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Signup_SignUpService_onsuccess_mapping_0"] = {
        "homeScreen": "Signup",
        "directions": []
    };
    Apperyio.mappings["Signup_SignUpService_onbeforesend_mapping_0"] = {
        "homeScreen": "Signup",
        "directions": [
            {
                "from_name": "Signup",
                "from_type": "UI",
                "to_name": "SignUpService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['lblUserName:text']",
                        "target": "$['body']['username']"
                    },
                    {
                        "source": "$['lblPassword:text']",
                        "target": "$['body']['password']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.SignUpService = Apperyio.datasources.SignUpService = new Apperyio.DataSource(Log_InandSign_Up_database_signup_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Signup_SignUpService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Signup_SignUpService_onsuccess_mapping_0"]);
            alert("Error: Successfully Registered");
            Apperyio.navigateTo('Login', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("Username already Registered");
        }
    });
    Apperyio.CurrentScreen = 'Signup';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Signup_onLoad = function() {
        Signup_elementsExtraJS();
        Signup_deviceEvents();
        Signup_windowEvents();
        Signup_elementsEvents();
    };
    // screen window events
    function Signup_windowEvents() {
        $('#Signup').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Signup_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Signup_elementsExtraJS() {
        // screen (Signup) extra code
    };
    // screen elements handler
    function Signup_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Signup_mobilecontainer [name="btnSignUp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        SignUpService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#Signup_mobilecontainer [name="btnSignUp"]');
    };
    $(document).off("pagebeforeshow", "#Signup").on("pagebeforeshow", "#Signup", function(event, ui) {
        Apperyio.CurrentScreen = "Signup";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Signup_onLoad();
};
$(document).off("pagecreate", "#Signup").on("pagecreate", "#Signup", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Signup_js();
});