/*
 * JS for View_Answer generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '97c28bfd-366a-4acc-9168-d1f20dc6a133';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ReportPage",
    "location": "ReportPage.html"
}, {
    "name": "StudentGuide",
    "location": "StudentGuide.html"
}, {
    "name": "Choose",
    "location": "Choose.html"
}, {
    "name": "Signup",
    "location": "Signup.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "Give_Answer",
    "location": "Give_Answer.html"
}, {
    "name": "View_Answer",
    "location": "View_Answer.html"
}, {
    "name": "Ask_a_Question",
    "location": "Ask_a_Question.html"
}, {
    "name": "About_Us",
    "location": "About_Us.html"
}, {
    "name": "QuestionandAnswer",
    "location": "QuestionandAnswer.html"
}];

function View_Answer_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblSelectQuestion': 'View_Answer_lblSelectQuestion',
        'sltSelectQuestion': 'View_Answer_sltSelectQuestion',
        'sltSelectQuestion-0': 'View_Answer_sltSelectQuestion-0',
        'lblViewQuestion': 'View_Answer_lblViewQuestion',
        'spacer_7': 'View_Answer_spacer_7',
        'lblShowDescription': 'View_Answer_lblShowDescription',
        'mobilegrid_2': 'View_Answer_mobilegrid_2',
        'gridListAll': 'View_Answer_gridListAll',
        'lblViewAnswer': 'View_Answer_lblViewAnswer'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["View_Answer_sltSelectQuestion_onchange_mapping_0"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "from_name": "View_Answer",
                "from_type": "UI",
                "to_name": "QuestionStore2",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['sltSelectQuestion:selectedMenuItem']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["View_Answer_sltSelectQuestion_onchange_mapping_1"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "from_name": "QuestionStore2",
                "from_type": "LOCAL_STORAGE",
                "to_name": "View_Answer",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['lblViewQuestion:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["View_Answer_listQuestions_onsuccess_mapping_0"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "from_name": "listQuestions",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "View_Answer",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$['sltSelectQuestion-0']"
                    },
                    {
                        "source": "$['body'][i]['Question']",
                        "target": "$['sltSelectQuestion-0:value']"
                    },
                    {
                        "source": "$['body'][i]['Question']",
                        "target": "$['sltSelectQuestion-0:label']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["View_Answer_listQuestions_onbeforesend_mapping_0"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "to_name": "listQuestions",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["View_Answer_searchSelectedQuestion_onsuccess_mapping_0"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "from_name": "searchSelectedQuestion",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "View_Answer",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]['Answer']",
                        "target": "$['mobilegrid_2']['lblViewAnswer:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target": "$['mobilegrid_2']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["View_Answer_searchSelectedQuestion_onbeforesend_mapping_0"] = {
        "homeScreen": "View_Answer",
        "directions": [
            {
                "from_name": "View_Answer",
                "from_type": "UI",
                "to_name": "searchSelectedQuestion",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['sltSelectQuestion:selectedMenuItem']",
                        "target_transformation": function(value) {
                            return '{"Question":"' + value + '"}';
                        },
                        "target": "$['parameters']['where']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.listQuestions = Apperyio.datasources.listQuestions = new Apperyio.DataSource(Question_and_Answer_Question_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["View_Answer_listQuestions_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["View_Answer_listQuestions_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.searchSelectedQuestion = Apperyio.datasources.searchSelectedQuestion = new Apperyio.DataSource(Question_and_Answer_Question_and_Answer_Collection_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["View_Answer_searchSelectedQuestion_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["View_Answer_searchSelectedQuestion_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'View_Answer';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var View_Answer_onLoad = function() {
        View_Answer_elementsExtraJS();
        try {
            listQuestions.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        View_Answer_deviceEvents();
        View_Answer_windowEvents();
        View_Answer_elementsEvents();
    };
    // screen window events
    function View_Answer_windowEvents() {
        $('#View_Answer').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function View_Answer_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function View_Answer_elementsExtraJS() {
        // screen (View_Answer) extra code
        /* sltSelectQuestion */
        $("#View_Answer_sltSelectQuestion").parent().find("a.ui-btn").attr("tabindex", "3");
    };
    // screen elements handler
    function View_Answer_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("change", '#View_Answer_mobilecontainer [name="sltSelectQuestion"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["View_Answer_sltSelectQuestion_onchange_mapping_0"]);
                Apperyio.processMappingAction(Apperyio.mappings["View_Answer_sltSelectQuestion_onchange_mapping_1"]);
                try {
                    searchSelectedQuestion.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        }, '#View_Answer_mobilecontainer [name="sltSelectQuestion"]');
    };
    $(document).off("pagebeforeshow", "#View_Answer").on("pagebeforeshow", "#View_Answer", function(event, ui) {
        Apperyio.CurrentScreen = "View_Answer";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    View_Answer_onLoad();
};
$(document).off("pagecreate", "#View_Answer").on("pagecreate", "#View_Answer", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    View_Answer_js();
});